# Theming
font: NotoSansM Nerd Font 14
background: "#fcf8ec"
color: "#210f1a"
border: "#d968ac"
separator: "  âžœ  "
border_width: 4
corner_r: 10
padding: 16

anchor: center
margin_right: 0
margin_bottom: 12
margin_left: 0
margin_top: 0

# namespace: "launcher"

inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true

menu:
  - key: "b"
    desc: brightness
    submenu:
      - key: "m"
        desc: ddcutil setvcp 10 100
        cmd: ddcutil setvcp 10 100
      - key: "n"
        desc: ddcutil setvcp 10 0
        cmd: ddcutil setvcp 10 0
  - key: "p"
    desc: power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: reboot
      - key: "o"
        desc: Off
        cmd: poweroff
  - key: "v"
    desc: volume
    submenu:
      - key: "j"
        desc: down
        cmd: volctl down
        keep_open: true
      - key: "k"
        desc: up
        cmd: volctl up
        keep_open: true
      - key: "m"
        desc: mute
        cmd: volctl toggle
        keep_open: true
      - key: "c"
        desc: cycle
        cmd: volctl cycle
        keep_open: true
  - key: "d"
    desc: run
    submenu:
      - key: "w"
        desc: zen-browser
        cmd: zen-browser
      - key: "p"
        desc: prismlauncher
        cmd: prismlauncher
      - key: "s"
        desc: steam
        cmd: steam
      - key: "d"
        desc: discord
        cmd: discord&discover-overlay
      - key: "n"
        desc: sunshine
        cmd: sunshine
      - key: "o"
        desc: obsidian
        cmd: obsidian
      - key: "k"
        desc: keepass
        cmd: keepassxc
      - key: "l"
        desc: libreoffice
        cmd: libreoffice
      - key: "g"
        desc: gimp
        cmd: gimp
      - key: "m"
        desc: music
        cmd: spotify-launcher
      - key: "v"
        desc: volume
        cmd: alacritty -e wiremix -v output -s extracompat
      - key: "space"
        desc: fuzzel
        cmd: fuzzel
  - key: "w"
    desc: windows
    cmd: niri:window-picker
