[font]
size = 16.0

[font.normal]
family = "ComicShannsMono Nerd Font"

[colors.normal]
black = "#282828"
red = "#ca1444"
green = "#789aba"
yellow = "#b3879f"
blue = "#94469b"
magenta = "#cb6fa1"
cyan = "#fb6e93"
white = "#cf98c1"

[colors.bright]
black = "#98218e"
red = "#cb515d"
green = "#5a87b1"
yellow = "#9c61ab"
blue = "#9a77b1"
magenta = "#f2a297"
cyan = "#f4436f"
white = "#ebdbb2"

[colors.primary]
background = "#fcf8ec"
foreground = "#210f1a"
